FROM ubuntu
RUN echo hi
LABEL org.opencontainers.image.authors="Test User"
LABEL org.opencontainers.image.name="test-image:latest"
LABEL org.opencontainers.image.branch="cicd-python/cuda"
LABEL org.opencontainers.image.version="1.0.0"
LABEL org.opencontainers.image.devmode="false"
LABEL org.opencontainers.image.scan="true"
LABEL org.opencontainers.image.platform="x86"
