FROM alpine:3.20
CMD ["sh", "-c", "echo smoke-ok"]
LABEL org.opencontainers.image.authors="alex@lings.ai"
LABEL org.opencontainers.image.name="smoke"
LABEL org.opencontainers.image.version="1.0.1"
LABEL org.opencontainers.image.devmode="true"
LABEL org.opencontainers.image.scan="false"
LABEL org.opencontainers.image.platform="x86"
