FROM python:3.9
RUN pip install fastapi
CMD ["python", "app.py"]
LABEL org.opencontainers.image.version="1.0.0"
LABEL org.opencontainers.image.devmode="false"
LABEL org.opencontainers.image.scan="true"
LABEL org.opencontainers.image.platform="x86"
