FROM ubuntu:20.04
ARG CUDA_VERSION=12.3
ARG PYTHON_VERSION=3.9
RUN echo $CUDA_VERSION
LABEL org.opencontainers.image.version="1.0.0"
LABEL org.opencontainers.image.devmode="false"
LABEL org.opencontainers.image.scan="true"
LABEL org.opencontainers.image.platform="x86"
